Eqtl hail batch (#95)
* Moving scripts from repo ancestry to appropriate repo, tob-wgs

See all previous commits here: https://github.com/populationgenomics/ancestry/tree/eqtl_hail_batch/scripts/hail_batch/eqtl_hail_batch

* Move entire folder to within scripts folder

* Use cloudpathlib to read in files

* Remove instances where input data are loaded in as separate batch jobs

* Add in print statements to debug OOM error

* Add in a few mor eprint statements, since the others successfully finished

* Add in more print statements to continue debugging

* Call functions inline to avoid memory issues

As per Leo's suggestion in this thread: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1648708175593959?thread_ts=1648620530.061689&cid=C030X7WGFCL

* Temporarily remove to_csv command

This may be causing the error: `ImportError: Missing optional dependency 'fsspec'`. See https://batch.hail.populationgenomics.org.au/batches/30502/jobs/1

* Load files within function itself

* Update driver image

* Load in mt

* Uncomment TOB_WGS file path

Tjis obviously led to the error that there was no file TOB_WGS

* Add in genotype information as hail matrix table

Add in genotype data as matrix table. Additionally, perform spearman rank correlation on genotype data of matrix table entries.

* Make loop over table more efficient

Michael and I worked on making getting SNPs from the hail table more efficient by persisting it, as well as keying it by the snpid.

* Reorganise code chunks for more logical flow

* Add a to of print statements to debug

* Only test on two genes and add in more print statements (for debug)

* Fix mt.head() to mt.show()

* Filter mt to only chr22

* Create snploc_df from hail mt

I had to remove the input snploc_df, since this had a differnet set of snps from what we have (after filtering with the new filters)

* Make checkpoint table unique

* Overwite checkpoint table instead, to make unique

* Test using checkpoint table for each gene/idx

This may solve the issue I'm getting for 'No such object' error: https://batch.hail.populationgenomics.org.au/batches/50054/jobs/1

* Add in entire filtering script, rather than just test

* Remove old mt path

* Peer programming check

Co-authored-by: Katalina Bobowik <katalina.bobowik@populationgenomics.org.au>

* add params

* Change ordering of code for more logical flow and fix old comments

* Update and remove old comments

* Add in copy_common_env command to fix 'assert billing_project' error

* Fix incorrect name of hail function

* Add in an exception if mt file already exists

* Return matrix table path

* Add init_batch() command before calling hl.hadoop_exists()

* Update wrapper script after removing genotype and snploc files

* Update README

* Add in cloudpathlibs AnyPath

* Try and debug correlation matrix by adding print statements

* Uodate 22 to chr22

* Run association analysis on unfiltered dataset

* Export entries table to pandas df before loop

* Add in print statements to debug

* Add in more print statements to debug

* Save table for debugging

* Remove variants that have no alt_allele genotype info

* Remove alleles, as this is redundant

* Only use samples that have covariate info

* Load in expression_df before it's called

Fix error referenced here: https://batch.hail.populationgenomics.org.au/batches/55418/jobs/2

* Add highmem workers and increase CPUs to 8

* Update round2 to mirror round1

* Fix residual df calculation

* Add in genotype file into calculating residuals function

* Save residuals and log cpm file using cloupathlib's AnyPath

* Update README

* Add conditional statement for filtering SNPs that do not have an alt_allele value

* Add in init_batch() command

I needed to remove this before, since I was just testing the function

* Update README

* Load in residual and sig SNPs file without batch.call()

* Load in sign snps and residual df before they're referenced

* Fix assert billing_project by adding copy_common_env()

* Add in comment to make residual df be calculated in next iretation of loop

* Update get_number_of_scatters to return all genes

* Fix pylint errors

* Remove unused library

* Update cpg_utils name and to_csv syntax

Matt recently made  updates to the cpg_utils library, so I renamed this from cpg_utils.hail to cpg_utils.hail_batch. I also changed the syntax of how I save csv files after following Vlad's recommendation in this thread: https://centrepopgen.slack.com/archives/C030X7WGFCL/p1649916338104869

* Temporarily use cpg_utils.hail, since cpg_utils.hail_batch doesn't work yet

* Change bsck to cpg_utils.hail_batch

cpg_utils.hail doesn't exist anymore

* Change PC names to lowercase

* Launch calculate_residuals only once using hail batch job

Otherwise, this command is unnecessarily duplicated

* Only calculate log cpm once in hail batch job

* Update cpg_utils.hail_batch

* Add in print statements to debug

* Reduce genes to 5 to test

* Add in debug orint statement and remove init_batch() (potential source of error)

* Incorporate hail table after successful last run (this may be causing the error)

* Unhash hail batch section

Table seemed to work before, so now I'm running everything else to see if it works

* Change ordering of spearman_correlation() for more logical flow

* Filter mt to improve speed of generating genotype

* Fix limter issue (double vs single quotes)

* Filter mt to save computational time

* Remove hard-coding of chromosome

* Add in test genes, along with pseudo code to get started on gene subsetting

* Add genes to  test in scatter

Only execute jobs if get_number_of_scatters() is not empty

* Only run hail batch if genes are contained within 'genes_to_test' vector

* Add in extra gene in test gene set that is in chr22 test genotype

* Add extra gene 'HDHD5' to all instances of genes_to_test

I left this gene out of a few instances of the genes_to_test variable (which is why th elast run initially failed with the error ""single positional indexer is out-of-bounds" (since there were no common genes at all without HDHD5). I also filtered the residual df so that it takes less time to compute

* Update covariates path

* Remove NA values when merging expression and covariate dfs

Previously, I was getting the error "ValueError: Length of values (960) does not match length of index (957)", and this was because the dmatrices linear model excludes NA values, which were present in the merged covariate + expression df. I therefore removed these NA values by using dropna()

* Update how significant snps df is read in

This is temporary, as I'm debugging

* Filter out NA values and fix residual df smaple ids

My previous job wasn't working due to the error "ValueError: zero-size array to reduction operation maximum which has no identity" (see https://batch.hail.populationgenomics.org.au/batches/70048/jobs/5). I realised that the problem behind this is that I incorrectly labelled the sampleids in the residual df after filtering. These new sampleids should be correct. I also filtered out any NA values in the spearman rank correlation so that I don't have any NA p-values or FDR values.

* Add in print statements to debug

as per the error message 'AttributeError: 'DataFrame' object has no attribute 'sampleid' in the log located here: https://batch.hail.populationgenomics.org.au/batches/70126/jobs/6

* Add in more print statements to debug

* Add more print statements to debug

* Add even more print statements to debug

I'm really focusing on printing statements within the function get_genotype_df(), since I believe this is where the error is happening.

* Testing commit

* Remove commented out code

This was used for testing/debugging puposes

* Add in more print statements within calculate_residual_df() to debug

* CHange print statement to print residual matrix, rather than unaassigned adjusted_residual_mat

* Add sampleid as a list and reassign in same way as previous script

* Remove undefined name 'sample_ids'

* Make gene_ids into a list before assignment to residual_df

* Tidy up script for PR to main

Remove all print statements and fix typos

* Remove unnecessary output_prefix in run_spearman_correlation_scatter()

* Remove print statements

Remove all unnecessary print statements and tidy up code for PR to main

* Update wrapper script after ne wchanges

* update paths to residual and significant correlation files

* Update README

* Rename round2 conditional file

* Rename conditional analysis script

This script doesn't just run round2, but rather runs all conditional analyses

* Update file names after renaming

* Rename wrapper script

* Update names in README after renaming

* Update README

* Remove unnecessary 'eqtl_results_' prefix

* Update '.' to '_' in wrapper script, for consistency

* Remove unnecessary 'test' from file name

* Get access level from input path, rather than manually adding it

* Fix linter issue "missing whitespace around operator"

* Remove hardcoding and fix indentation, as per Vlad's suggestions

You can see the conversation here: https://github.com/populationgenomics/tob-wgs/pull/95

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Fix indentation of if statement, as per Michael's suggestions on conditional_analysis.py script

* Fix linter errors

* Remove unnecessary highmem and cpu request to analysis runner

Analysis runner simply loads in files and moves work to batch workflow

* Test qvalues using multipy.fdr package

* Update name of covariates file

These files on test should mirror what is on main

* Add in link to J Powell's OneK1K paper code

As per Matt Welland's request

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Matt Welland <mattwellie@gmail.com>

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Matt Welland <mattwellie@gmail.com>

* Update scripts/eqtl_hail_batch/generate_eqtl_spearman.py

Co-authored-by: Matt Welland <mattwellie@gmail.com>

* Update scripts/eqtl_hail_batch/generate_eqtl_spearman.py

Co-authored-by: Matt Welland <mattwellie@gmail.com>

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Matt Welland <mattwellie@gmail.com>

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Matt Welland <mattwellie@gmail.com>

* Fix all instances of iteration+2 and positional argument order.

As per Matt Welland's helpful comment, range(2, iterations +2) can be used to add t initially to each iteration. This saves me from adding +2 to to each instance of iteration. In addition, I fixed the ordering of the sampleid positional argument, as I was getting the error ‘positional argument cannot appear after keyword arguments’.

* FIx 'missing whitespace around operator' linter issue

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update scripts/eqtl_hail_batch/README.md

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update scripts/eqtl_hail_batch/launch_conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update image

Update image in generate_eqtl_spearman.py and conditional analysis script, so that it can load in the multipy package (for FDR correction using qvalues). I have also updated the wrapper scripts and README, so that it includes the inclusion of the --image argument when invoking the analysis runner.

* Change 'PC' in linear model to uppercase

Change this in order to fit with updated peer factor file (mirror of what is on main).

* Add more detail on expected file format

Update docsttrings to describe input and output file formats, as suggested by Katie.

* Expand comments for all functions to include input and output values
 #Please enter the commit message for your changes. Lines starting

* Expand help functions to include detail on the expected file format

* Update comments to reflect I am filtering at MAF <= 0.01

* Update README to reflect workflow

Taken from Katie's suggestions here: https://github.com/populationgenomics/tob-wgs/pull/95#discussion_r884198322

* Fix markdown formatting to make headers appear

* Update markdown formatting for numbered list

* Rearrange ordering of output stataments for better flow

* Add extra carriage return to make output appear on new line

* Bold different sections of the analysis, to differentiate steps

* Add in Pipeline output specification

As outlined by Daniel Esposito in https://github.com/populationgenomics/tob-wgs/issues/97#event-6714111281

* Update config parameter

https://centrepopgen.slack.com/archives/C018KFBCR1C/p1653529942491209

* Fix syntax of get_config import

Following this instead https://github.com/populationgenomics/automated-interpretation-pipeline/blob/ab93ddaab357f9931a5586e1618688740766a6b4/reanalysis/comparison_wrapper.py#L28

* Fix space after commas (linter issue)

* Make changes to multipy to make the changes to driver image more solid

See recommendations from Michael: https://github.com/populationgenomics/tob-wgs/pull/95#pullrequestreview-994409602

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update driver image

* Hash out new code to see where script is failing

* Add in cpg_utils.config

* Add in print statements to debug spearman_df output failing

* Fix error when adding in new columns

getting the error: 'Pandas doesn't allow columns to be created via a new attribute name'. Solved as in this Stack Overflow post: https://stackoverflow.com/questions/53178162/userwarning-pandas-doesnt-allow-columns-to-be-created-via-a-new-attribute-name

* Add in gene_expression.parquet file

Add in file, exported as a parquet, which gathers information for the logCPM data. All requirements for the file can be found under Gene expression distribution (logCPM) in github file here https://github.com/populationgenomics/tob-wgs/issues/97

* Add celltype into calculate_log_cpm when called by batch

* Debug 'binary file expected, got text file' error

Hash out part where I save the file, which where I think the issue is

* Forgot to save file, now writing out file is commented out

* Unhash saving paruet file after removing index = False

Index = False is specific to CSV files, so I'v etried omitting this to see if it works

* Save parquet file directly, instead of opening

* Change writing parquet as 'w' to binary 'wb'

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Update scripts/eqtl_hail_batch/conditional_analysis.py

Co-authored-by: Michael Franklin <michael@illusional.net>

* Add extra comments for clarity, as per Michael's comments

Co-authored-by: Michael Franklin <michael.franklin@populationgenomics.org.au>
Co-authored-by: Michael Franklin <michael@illusional.net>
Co-authored-by: Matt Welland <mattwellie@gmail.com>